language: node_js
node_js:
  - "7"
cache:
  directories:
    - "node_modules"
after_success:
  - npm install lib.cli -g
  - lib init -n
  - lib login --email $STDLIB_EMAIL --password $STDLIB_PASSWORD
  - lib release
