language: node_js
node_js:
  - "7"
cache:
  directories:
    - "node_modules"
after_success:
  - npm install lib.cli -g
  - lib init -t $STDLIB_ACCESS_TOKEN
  - lib login --email $STDLIB_EMAIL --password $STDLIB_PASSWORD
  - lib release
