language: node_js
node_js:
  - "11"
cache:
  directories:
    - "node_modules"
deploy:
  provider: script
  script: npm install lib.cli -g && echo "ACCESS_TOKEN=$STDLIB_ACCESS_TOKEN" > ~/.librc && lib release
  on:
    branch: master
  