language: node_js
node_js:
  - "7"
cache:
  directories:
    - "node_modules"
deploy:
  provider: script
  script: chmod +x $TRAVIS_BUILD_DIR/scripts/deploy.sh && $TRAVIS_BUILD_DIR/scripts/deploy.sh
  on:
    branch: master
  